# Generated by Django 2.0.2 on 2018-02-25 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device_Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('age', models.IntegerField(blank=True)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('height', models.IntegerField(blank=True)),
                ('heart_rate_max', models.IntegerField(blank=True)),
                ('heart_rate_zone1_low', models.IntegerField(blank=True)),
                ('heart_rate_zone1_high', models.IntegerField(blank=True)),
                ('heart_rate_zone2_low', models.IntegerField(blank=True)),
                ('heart_rate_zone2_high', models.IntegerField(blank=True)),
                ('heart_rate_zone3_low', models.IntegerField(blank=True)),
                ('heart_rate_zone3_high', models.IntegerField(blank=True)),
                ('heart_rate_zone4_low', models.IntegerField(blank=True)),
                ('heart_rate_zone5_high', models.IntegerField(blank=True)),
            ],
        ),
    ]
