# Generated by Django 2.0.2 on 2018-02-25 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myfit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('device_serial_no', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('device_model', models.CharField(max_length=100)),
                ('device_name', models.CharField(max_length=100)),
                ('device_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myfit.Device_Owner')),
            ],
        ),
    ]
