# Generated by Django 2.0.2 on 2018-02-25 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfit', '0002_device'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device_owner',
            name='height',
        ),
        migrations.AlterField(
            model_name='device_owner',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='device_owner',
            name='heart_rate_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='device_owner',
            name='heart_rate_zone1_high',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='device_owner',
            name='heart_rate_zone1_low',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='device_owner',
            name='heart_rate_zone2_high',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='device_owner',
            name='heart_rate_zone2_low',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='device_owner',
            name='heart_rate_zone3_high',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='device_owner',
            name='heart_rate_zone3_low',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='device_owner',
            name='heart_rate_zone4_low',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='device_owner',
            name='heart_rate_zone5_high',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
