# Generated by Django 2.0.2 on 2018-02-25 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfit', '0003_auto_20180225_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='device_owner',
            name='heart_rate_zone4_high',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device_owner',
            name='heart_rate_zone5_low',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
