# Generated by Django 2.0.2 on 2018-02-25 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfit', '0004_auto_20180225_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='device_owner',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
    ]
