# Generated by Django 2.0.2 on 2018-02-25 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfit', '0005_device_owner_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='device_owner',
            name='heart_rate_rest',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='device_owner',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device_owner',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
    ]
