# Generated by Django 2.0.2 on 2018-03-05 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myfit', '0006_auto_20180225_2312'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('activity_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('activity_time_original', models.CharField(max_length=20)),
                ('activity_date', models.DateField()),
                ('activity_time', models.TimeField()),
                ('activity_duration', models.IntegerField(default=0)),
                ('activity_duration_hh', models.IntegerField(default=0)),
                ('activity_duration_mm', models.IntegerField(default=0)),
                ('activity_duration_ss', models.IntegerField(default=0)),
                ('activity_speed_max', models.DecimalField(decimal_places=3, max_digits=5)),
                ('activity_speed_avg', models.DecimalField(decimal_places=3, max_digits=5)),
                ('activity_hr_max', models.IntegerField(default=0)),
                ('activity_hr_min', models.IntegerField(default=0)),
                ('activity_hr_avg', models.IntegerField(default=0)),
                ('activity_type', models.IntegerField(default=0)),
                ('activity_type_name', models.CharField(max_length=200)),
                ('activity_device_used', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myfit.Device')),
            ],
        ),
        migrations.AlterField(
            model_name='device_owner',
            name='age',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='device_owner',
            name='heart_rate_max',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='device_owner',
            name='heart_rate_rest',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='device_owner',
            name='heart_rate_zone1_high',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='device_owner',
            name='heart_rate_zone1_low',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='device_owner',
            name='heart_rate_zone2_high',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='device_owner',
            name='heart_rate_zone2_low',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='device_owner',
            name='heart_rate_zone3_high',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='device_owner',
            name='heart_rate_zone3_low',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='device_owner',
            name='heart_rate_zone4_high',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='device_owner',
            name='heart_rate_zone4_low',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='device_owner',
            name='heart_rate_zone5_high',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='device_owner',
            name='heart_rate_zone5_low',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
