# Generated by Django 2.0.2 on 2018-04-14 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfit', '0009_auto_20180313_0233'),
    ]

    operations = [
        migrations.AddField(
            model_name='device_owner',
            name='log_files_location',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
